# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtWebEngineWidgets
import photo_rc
import sys
from viwe import *
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap, QMouseEvent
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QTableWidgetItem, QTableWidget, QWidget
from PyQt5.QtCore import QThread, pyqtSignal
from PyQt5.QtCore import Qt, QPoint, QUrl
import matplotlib.pyplot as plt
import photo_rc
import csv
# from test import eval_one,Model
from test import *
import torch
from all_Thread import cluster_Thread, analyze_Thread
import pandas as pd
from bert import predict
import shutil
filepath = None
cluter = False
image = False


class Second_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1490, 857)
        Form.setStyleSheet("#Form{\n"
                           "    ;\n"
                           "    border-image: url(:/111/photo/20220828131919_adb62.jpg);\n"
                           "}")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(267, 107, 441, 24))
        self.lineEdit.setStyleSheet("background-color: rgba(255, 255, 255, 100);")
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(119, 79, 151, 81))
        self.label_3.setStyleSheet("image: url(:/111/photo/img1717565523966.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 10, 111, 51))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
                                        "border-radius:15px;    /*设置圆角半径 */\n"
                                        "padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
                                        "background-color: rgba(0,191,255,200);    /*背景颜色*/\n"
                                        "color:white;        /*字体颜色*/\n"
                                        "min-width:20px;    /*设置最小宽度*/\n"
                                        "min-height:20px;    /*设置最小高度*/\n"
                                        "font:bold 14px;        /*设置按钮文字和大小*/\n"
                                        "}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 70, 111, 51))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
                                        "border-radius:15px;    /*设置圆角半径 */\n"
                                        "padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
                                        "background-color: rgba(230,230,250,200);    /*背景颜色*/\n"
                                        "color:white;        /*字体颜色*/\n"
                                        "min-width:20px;    /*设置最小宽度*/\n"
                                        "min-height:20px;    /*设置最小高度*/\n"
                                        "font:bold 14px;        /*设置按钮文字和大小*/\n"
                                        "}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(719, 99, 91, 41))
        self.pushButton.setStyleSheet("QPushButton{\n"
                                      "border:1px solid white; \n"
                                      "border-radius:15px;    /*设置圆角半径 */\n"
                                      "padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
                                      "background-color: rgb(230,230,250);    /*背景颜色*/\n"
                                      "color:white;        /*字体颜色*/\n"
                                      "min-width:20px;    /*设置最小宽度*/\n"
                                      "min-height:20px;    /*设置最小高度*/\n"
                                      "font:bold 14px;        /*设置按钮文字和大小*/\n"
                                      "}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(870, 150, 111, 41))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
                                        "border:1px solid white; \n"
                                        "border-radius:15px;    /*设置圆角半径 */\n"
                                        "padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
                                        "background-color: rgb(230,230,250);    /*背景颜色*/\n"
                                        "color:white;        /*字体颜色*/\n"
                                        "min-width:20px;    /*设置最小宽度*/\n"
                                        "min-height:20px;    /*设置最小高度*/\n"
                                        "font:bold 14px;        /*设置按钮文字和大小*/\n"
                                        "}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(140, 160, 91, 41))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
                                        "border:1px solid white; \n"
                                        "border-radius:15px;    /*设置圆角半径 */\n"
                                        "padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
                                        "background-color: rgb(230,230,250);    /*背景颜色*/\n"
                                        "color:white;        /*字体颜色*/\n"
                                        "min-width:20px;    /*设置最小宽度*/\n"
                                        "min-height:20px;    /*设置最小高度*/\n"
                                        "font:bold 14px;        /*设置按钮文字和大小*/\n"
                                        "}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(600, 160, 111, 31))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
                                        "border:1px solid white; \n"
                                        "border-radius:15px;    /*设置圆角半径 */\n"
                                        "padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
                                        "background-color: rgb(230,230,250);    /*背景颜色*/\n"
                                        "color:white;        /*字体颜色*/\n"
                                        "min-width:20px;    /*设置最小宽度*/\n"
                                        "min-height:20px;    /*设置最小高度*/\n"
                                        "font:bold 14px;        /*设置按钮文字和大小*/\n"
                                        "}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(360, 160, 231, 31))
        self.comboBox.setStyleSheet("QComboBox {\n"
                                    "                border: 1px solid gray;\n"
                                    "                border-radius: 5px;\n"
                                    "                padding: 1px 18px 1px 3px;\n"
                                    "                min-width: 6em;\n"
                                    "                color: white;\n"
                                    "            }\n"
                                    "\n"
                                    "            QComboBox:editable {\n"
                                    "                background: white;\n"
                                    "            }\n"
                                    "\n"
                                    "            QComboBox:!editable, QComboBox::drop-down:editable {\n"
                                    "                background: rgb(230,230,250);\n"
                                    "            }\n"
                                    "\n"
                                    "            QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
                                    "                background: lightblue;\n"
                                    "            }\n"
                                    "\n"
                                    "            QComboBox:on {\n"
                                    "                padding-top: 3px;\n"
                                    "                padding-left: 4px;\n"
                                    "            }\n"
                                    "\n"
                                    "            QComboBox::drop-down {\n"
                                    "                subcontrol-origin: padding;\n"
                                    "                subcontrol-position: top right;\n"
                                    "                width: 15px;\n"
                                    "                border-left-width: 1px;\n"
                                    "                border-left-color: darkgray;\n"
                                    "                border-left-style: solid;\n"
                                    "                border-top-right-radius: 3px;\n"
                                    "                border-bottom-right-radius: 3px;\n"
                                    "            }\n"
                                    "\n"
                                    "            QComboBox::down-arrow {\n"
                                    "                image: url(down_arrow.png);\n"
                                    "            }")
        self.comboBox.setObjectName("comboBox")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(260, 160, 101, 31))
        self.label_5.setStyleSheet("image: url(:/111/photo/img1717572147820.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(720, 160, 111, 31))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
                                        "border:1px solid white; \n"
                                        "border-radius:15px;    /*设置圆角半径 */\n"
                                        "padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
                                        "background-color: rgb(230,230,250);    /*背景颜色*/\n"
                                        "color:white;        /*字体颜色*/\n"
                                        "min-width:20px;    /*设置最小宽度*/\n"
                                        "min-height:20px;    /*设置最小高度*/\n"
                                        "font:bold 14px;        /*设置按钮文字和大小*/\n"
                                        "}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(70, 210, 1301, 611))
        self.tableWidget.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(1380, 10, 101, 51))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
                                        "border-radius:15px;    /*设置圆角半径 */\n"
                                        "padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
                                        "background-color: rgba(230,230,250,200);    /*背景颜色*/\n"
                                        "color:white;        /*字体颜色*/\n"
                                        "min-width:20px;    /*设置最小宽度*/\n"
                                        "min-height:20px;    /*设置最小高度*/\n"
                                        "font:bold 14px;        /*设置按钮文字和大小*/\n"
                                        "}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(1000, 160, 189, 21))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setStyleSheet("QRadioButton::indicator {\n"
                                       "                width: 15px;\n"
                                       "                height: 15px;\n"
                                       "                border-radius: 9px;\n"
                                       "                border: 2px solid rgb(230,230,250);\n"
                                       "                background-color: white;\n"
                                       "            }\n"
                                       "            QRadioButton::indicator:checked {\n"
                                       "                background-color:  rgb(230,230,250);\n"
                                       "                border: 2px solid #1E90FF;\n"
                                       "            }\n"
                                       "            QRadioButton {\n"
                                       "                font-size: 16px;\n"
                                       "                color:  rgb(0,191,255,);\n"
                                       "            }")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setStyleSheet("QRadioButton::indicator {\n"
                                         "                width: 15px;\n"
                                         "                height: 15px;\n"
                                         "                border-radius: 9px;\n"
                                         "                border: 2px solid rgb(230,230,250);\n"
                                         "                background-color: white;\n"
                                         "            }\n"
                                         "            QRadioButton::indicator:checked {\n"
                                         "                background-color:  rgb(230,230,250);\n"
                                         "                border: 2px solid #1E90FF;\n"
                                         "            }\n"
                                         "            QRadioButton {\n"
                                         "                font-size: 16px;\n"
                                         "                color:  rgb(0,191,255,);\n"
                                         "            }")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.brower1 = QtWebEngineWidgets.QWebEngineView(Form)
        self.brower1.setGeometry(QtCore.QRect(70, 210, 1301, 611))
        self.brower1.setObjectName("brower1")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(980, 160, 231, 31))
        self.comboBox_3.setStyleSheet("QComboBox {\n"
                                      "                border: 1px solid gray;\n"
                                      "                border-radius: 5px;\n"
                                      "                padding: 1px 18px 1px 3px;\n"
                                      "                min-width: 6em;\n"
                                      "                color: white;\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox:editable {\n"
                                      "                background: white;\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox:!editable, QComboBox::drop-down:editable {\n"
                                      "                background: rgb(230,230,250);\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
                                      "                background: lightblue;\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox:on {\n"
                                      "                padding-top: 3px;\n"
                                      "                padding-left: 4px;\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox::drop-down {\n"
                                      "                subcontrol-origin: padding;\n"
                                      "                subcontrol-position: top right;\n"
                                      "                width: 15px;\n"
                                      "                border-left-width: 1px;\n"
                                      "                border-left-color: darkgray;\n"
                                      "                border-left-style: solid;\n"
                                      "                border-top-right-radius: 3px;\n"
                                      "                border-bottom-right-radius: 3px;\n"
                                      "            }\n"
                                      "\n"
                                      "            QComboBox::down-arrow {\n"
                                      "                image: url(down_arrow.png);\n"
                                      "            }")
        self.comboBox_3.setObjectName("comboBox_3")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(140, 10, 311, 101))
        self.label.setStyleSheet("image: url(./photo/img1739783841743.png);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(380, 40, 631, 51))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(1030, 40, 121, 51))
        self.pushButton_9.setStyleSheet("QPushButton{\n"
                                        "border-radius:15px;    /*设置圆角半径 */\n"
                                        "padding:2px 4px;  /*QFrame边框与内部其它部件的距离*/\n"
                                        "background-color: rgba(0,191,255,200);    /*背景颜色*/\n"
                                        "color:white;        /*字体颜色*/\n"
                                        "min-width:20px;    /*设置最小宽度*/\n"
                                        "min-height:20px;    /*设置最小高度*/\n"
                                        "font:bold 14px;        /*设置按钮文字和大小*/\n"
                                        "}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(1200, 40, 111, 51))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setReadOnly(True)
        self.tableWidget.raise_()
        self.lineEdit.raise_()
        self.label_3.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.comboBox.raise_()
        self.label_5.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.layoutWidget.raise_()
        self.brower1.raise_()
        self.label.raise_()
        self.lineEdit_2.raise_()
        self.pushButton_9.raise_()
        self.lineEdit_3.raise_()
        self.comboBox_3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.pushButton.clicked.connect(self.openFile)
        self.pushButton_5.clicked.connect(self.cluster)
        self.pushButton_6.clicked.connect(self.analyze)
        self.pushButton_2.clicked.connect(self.save_fig)
        self.pushButton_8.clicked.connect(self.shutdown)
        self.pushButton_7.clicked.connect(self.draw_html)
        self.pushButton_9.clicked.connect(self.predict)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_3.setText(_translate("Form", "爬取微博内容"))
        self.pushButton_4.setText(_translate("Form", "舆情分析系统"))
        self.pushButton.setText(_translate("Form", "打开文件夹"))
        self.pushButton_2.setText(_translate("Form", "保存可视化图片"))
        self.pushButton_5.setText(_translate("Form", "话题聚类"))
        self.pushButton_6.setText(_translate("Form", "展示舆情分析"))
        self.pushButton_7.setText(_translate("Form", "对比可视化"))
        self.pushButton_8.setText(_translate("Form", "关闭"))
        self.radioButton.setText(_translate("Form", "HTML形式"))
        self.radioButton_2.setText(_translate("Form", "图片形式"))
        self.pushButton_9.setText(_translate("Form", "点击分析"))

    def predict(self):
        text = self.lineEdit_2.text()
        print(type(text))
        print(text)
        result = str(predict.bert_predict(text))
        print(type(result))
        self.lineEdit_3.setText(result)

    def openFile(self):  # 选择本地图片上传
        global filepath  # 这里为了方便别的地方引用图片路径，我们把它设置为全局变量
        global cluter
        filepath, imgType = QFileDialog.getOpenFileName(self, "打开数据文件", "",
                                                        "*.csv;;All Files(*)")  # 弹出一个文件选择框，第一个返回值imgName记录选中的文件路径+文件名，第二个返回值imgType记录文件的类型
        self.lineEdit.setText(filepath)  # 显示所选图片的本地路径
        cluter = False

    def cluster(self):
        global filepath
        if filepath is None or filepath == '':
            QMessageBox.information(self, "Error!", "请先选择数据文件！", QMessageBox.Ok)
            return
        self.pushButton_5.setEnabled(False)
        self.thread_1 = cluster_Thread(filepath)
        self.thread_1.cluster.connect(self.additem)
        self.thread_1.start()

    def additem(self, list1):
        global cluter
        global image
        # print("ui",list1)
        self.comboBox.addItems(list1)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setStyleSheet("background-color: rgba(255, 255, 255, 10);")
        image = False
        cluter = True

        image = True
        self.pushButton_5.setEnabled(True)
        self.comboBox_3.addItems(['各类总数饼图', '各类消极积极柱状图'])

    def analyze(self):
        global cluter
        global image
        if cluter is False:
            QMessageBox.information(self, "Error!", "请先进行聚类分析！", QMessageBox.Ok)
            return
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.brower1.setGeometry(QtCore.QRect(0, 0, 0, 0))
        image = False
        self.thread_2 = analyze_Thread(r'data/output.csv', self.comboBox.currentIndex())
        self.thread_2.ana_data.connect(self.add_TableItem)
        self.thread_2.start()

    def add_TableItem(self, list1):
        data, label = list1
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(len(data))
        self.tableWidget.setColumnWidth(0, 860)
        self.tableWidget.setVerticalScrollMode(QTableWidget.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QTableWidget.ScrollPerPixel)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setStyleSheet("alternate-background-color: #f0f0f0;")
        self.tableWidget.setHorizontalHeaderLabels(['内容', '情感'])
        for i in range(len(data)):
            self.tableWidget.setItem(i, 0, QTableWidgetItem(data[i]))
            self.tableWidget.setItem(i, 1, QTableWidgetItem(label[i]))

    def save_fig(self):
        filename, _ = QFileDialog.getSaveFileName(self, "Save file", "", "*.html;;All Files(*)")
        shutil.copyfile('output.html', filename)

    def mouseMoveEvent(self, e: QMouseEvent):  # 重写移动事件
        if self._tracking:
            self._endPos = e.pos() - self._startPos
            self.move(self.pos() + self._endPos)

    def mousePressEvent(self, e: QMouseEvent):
        if e.button() == Qt.LeftButton:
            self._startPos = QPoint(e.x(), e.y())
            self._tracking = True

    def mouseReleaseEvent(self, e: QMouseEvent):
        if e.button() == Qt.LeftButton:
            self._tracking = False
            self._startPos = None
            self._endPos = None

    def shutdown(self):
        self.destroy()  # 窗口关闭销毁
        sys.exit(0)

    def draw_html(self):
        global cluter
        if cluter is False:
            QMessageBox.information(self, "Error!", "还未进行聚类！", QMessageBox.Ok)
            return
        if self.comboBox_3.currentIndex() == 0:
            pie('data/output.csv')
            self.brower1.setGeometry(QtCore.QRect(70, 210, 1301, 611))
            self.brower1.load(QUrl('file:///output.html'))
        elif self.comboBox_3.currentIndex() == 1:
            bar2('data/output.csv')
            self.brower1.setGeometry(QtCore.QRect(70, 210, 1301, 611))
            self.brower1.load(QUrl('file:///output.html'))


class second_UI(QWidget, Second_Form):
    def __init__(self):
        super(second_UI, self).__init__()
        self.setupUi(self)
